import Morpho.Compiler.MacroSlice
import Verity.Core.Free.TypedIRCompilerCorrectness

/-!
# Compilation Correctness for Morpho Admin Functions

This module proves that all 5 admin function bodies generated by
`verity_contract MorphoViewSlice` are `SupportedStmtList`s, meaning the
generic typed-IR compilation-correctness theorem gives them free
compilation proofs (Links 2+3: EDSL ↔ IR ↔ Yul).

## Covered functions
1. **setOwner**: caller == owner, newOwner ≠ owner, setStorageAddr
2. **setFeeRecipient**: caller == owner, newFeeRecipient ≠ feeRecipient, setStorageAddr
3. **enableIrm**: caller == owner, mapping == 0, setMapping
4. **enableLltv**: caller == owner, mappingUint == 0, param < bound, setMappingUint
5. **setAuthorization**: caller, mapping2 read, ite bool, require, setMapping2
-/

namespace Morpho.Proofs.CompilationCorrectness

open Compiler.CompilationModel
open Verity.Core.Free
open Morpho.Compiler.MacroSlice

-- DecidableEq chain needed for `native_decide` on field resolution
deriving instance DecidableEq for PackedBits
deriving instance DecidableEq for MappingKeyType
deriving instance DecidableEq for MappingType
deriving instance DecidableEq for StructMember
deriving instance DecidableEq for FieldType
deriving instance DecidableEq for Field

/-- Concrete storage field layout matching what `verity_contract MorphoViewSlice`
generates. Fields whose explicit slot matches their list position use `none`
so that `findFieldWithResolvedSlot` returns a `Field` with default `slot := none`,
matching the pattern expected by `SupportedStmtFragment` constructors.
Fields at non-matching positions (marketSlot, idToMarketParamsSlot) keep
their explicit `some` overrides. -/
def morphoFields : List Field :=
  [ ⟨"ownerSlot", FieldType.address, none, none, []⟩
  , ⟨"feeRecipientSlot", FieldType.address, none, none, []⟩
  , ⟨"marketSlot", FieldType.mappingTyped (.simple .uint256), some 3, none, []⟩
  , ⟨"idToMarketParamsSlot", FieldType.mappingTyped (.simple .uint256), some 8, none, []⟩
  , ⟨"isIrmEnabledSlot", FieldType.mappingTyped (.simple .address), none, none, []⟩
  , ⟨"isLltvEnabledSlot", FieldType.mappingTyped (.simple .uint256), none, none, []⟩
  , ⟨"isAuthorizedSlot", FieldType.mappingTyped (.nested .address .address), none, none, []⟩
  , ⟨"nonceSlot", FieldType.mappingTyped (.simple .address), none, none, []⟩
  ]

/-! ## SupportedStmtList witnesses -/

/-! Upstream canonical witnesses (verity pin 9d9533b2) for Morpho admin patterns.
These are reference pattern theorems over verity-owned field layouts.
The morpho-specific proofs below keep our 8-field `morphoFields` layout. -/

theorem setOwner_supported_upstream :
    SupportedStmtList adminPatternFields
      [ Stmt.letVar "sender" Expr.caller
      , Stmt.letVar "ownerVar" (Expr.storage "owner")
      , Stmt.require (Expr.eq (Expr.localVar "sender") (Expr.localVar "ownerVar")) "not owner"
      , Stmt.require (Expr.logicalNot (Expr.eq (Expr.param "newOwner") (Expr.localVar "ownerVar")))
          "already owner"
      , Stmt.setStorage "owner" (Expr.param "newOwner")
      , Stmt.stop ] := by
  simpa using
    witness_letCallerLetStorageAddrReqEqReqNeqSetStorageAddrParamStop_owner_supported

theorem enableIrm_supported_upstream :
    SupportedStmtList morphoEnableIrmFields
      [ Stmt.letVar "sender" Expr.caller
      , Stmt.letVar "ownerVar" (Expr.storage "owner")
      , Stmt.require (Expr.eq (Expr.localVar "sender") (Expr.localVar "ownerVar")) "not owner"
      , Stmt.letVar "isEnabled" (Expr.mapping "isIrmEnabled" (Expr.param "irm"))
      , Stmt.require (Expr.eq (Expr.localVar "isEnabled") (Expr.literal 0)) "already enabled"
      , Stmt.setMapping "isIrmEnabled" (Expr.param "irm") (Expr.literal 1)
      , Stmt.stop ] := by
  simpa using
    witness_letCallerLetStorageAddrReqEqLetMappingReqEqLitSetMappingStop_enableIrm_supported

theorem enableLltv_supported_upstream :
    SupportedStmtList morphoEnableLltvFields
      [ Stmt.letVar "sender" Expr.caller
      , Stmt.letVar "ownerVar" (Expr.storage "owner")
      , Stmt.require (Expr.eq (Expr.localVar "sender") (Expr.localVar "ownerVar")) "not owner"
      , Stmt.letVar "isEnabled" (Expr.mappingUint "isLltvEnabled" (Expr.param "lltv"))
      , Stmt.require (Expr.eq (Expr.localVar "isEnabled") (Expr.literal 0)) "already enabled"
      , Stmt.require (Expr.lt (Expr.param "lltv") (Expr.literal 1000000000000000000))
          "lltv too high"
      , Stmt.setMappingUint "isLltvEnabled" (Expr.param "lltv") (Expr.literal 1)
      , Stmt.stop ] := by
  simpa using
    witness_letCallerLetStorageAddrReqEqLetMappingUintReqEqLitReqLtSetMappingUintStop_enableLltv_supported

theorem setAuthorization_supported_upstream :
    SupportedStmtList morphoSetAuthorizationFields
      [ Stmt.letVar "sender" Expr.caller
      , Stmt.letVar "isAuthorizedNow"
          (Expr.mapping2 "isAuthorized" (Expr.localVar "sender") (Expr.param "authorized"))
      , Stmt.ite (Expr.param "newIsAuthorized")
          [ Stmt.require (Expr.eq (Expr.localVar "isAuthorizedNow") (Expr.literal 0))
              "already authorized"
          , Stmt.setMapping2 "isAuthorized" (Expr.localVar "sender") (Expr.param "authorized")
              (Expr.literal 1) ]
          [ Stmt.require
              (Expr.logicalNot (Expr.eq (Expr.localVar "isAuthorizedNow") (Expr.literal 0)))
              "already not authorized"
          , Stmt.setMapping2 "isAuthorized" (Expr.localVar "sender") (Expr.param "authorized")
              (Expr.literal 0) ]
      , Stmt.stop ] := by
  simpa using
    witness_letCallerLetMapping2IteParamReqSetMapping2Stop_setAuthorization_supported

/-- The `setOwner` function body is a `SupportedStmtList`. -/
theorem setOwner_supported :
    SupportedStmtList morphoFields
      [ Stmt.letVar "sender" Expr.caller
      , Stmt.letVar "currentOwner" (Expr.storage "ownerSlot")
      , Stmt.require (Expr.eq (Expr.localVar "sender") (Expr.localVar "currentOwner")) "not owner"
      , Stmt.require (Expr.logicalNot (Expr.eq (Expr.param "newOwner") (Expr.localVar "currentOwner"))) "already set"
      , Stmt.setStorage "ownerSlot" (Expr.param "newOwner")
      , Stmt.stop ] :=
  ⟨[.letCallerLetStorageAddrReqEqReqNeqSetStorageAddrParamStop
    "ownerSlot" "sender" "currentOwner" "newOwner" "not owner" "already set" 0
    (by native_decide) (by decide) (by decide) (by decide)], rfl⟩

/-- The `setFeeRecipient` function body is a `SupportedStmtList`. -/
theorem setFeeRecipient_supported :
    SupportedStmtList morphoFields
      [ Stmt.letVar "sender" Expr.caller
      , Stmt.letVar "currentOwner" (Expr.storage "ownerSlot")
      , Stmt.require (Expr.eq (Expr.localVar "sender") (Expr.localVar "currentOwner")) "not owner"
      , Stmt.letVar "currentFeeRecipient" (Expr.storage "feeRecipientSlot")
      , Stmt.require
          (Expr.logicalNot (Expr.eq (Expr.param "newFeeRecipient") (Expr.localVar "currentFeeRecipient")))
          "already set"
      , Stmt.setStorage "feeRecipientSlot" (Expr.param "newFeeRecipient")
      , Stmt.stop ] :=
  ⟨[.letCallerLetStorageAddrReqEqLetStorageAddrReqNeqSetStorageAddrParamStop
    "ownerSlot" "feeRecipientSlot" "sender" "currentOwner" "currentFeeRecipient" "newFeeRecipient"
    0 1 "not owner" "already set"
    (by native_decide) (by native_decide) (by decide) (by decide) (by decide) (by decide)], rfl⟩

/-- The `enableIrm` function body is a `SupportedStmtList`. -/
theorem enableIrm_supported :
    SupportedStmtList morphoFields
      [ Stmt.letVar "sender" Expr.caller
      , Stmt.letVar "currentOwner" (Expr.storage "ownerSlot")
      , Stmt.require (Expr.eq (Expr.localVar "sender") (Expr.localVar "currentOwner")) "not owner"
      , Stmt.letVar "currentValue" (Expr.mapping "isIrmEnabledSlot" (Expr.param "irm"))
      , Stmt.require (Expr.eq (Expr.localVar "currentValue") (Expr.literal 0)) "already set"
      , Stmt.setMapping "isIrmEnabledSlot" (Expr.param "irm") (Expr.literal 1)
      , Stmt.stop ] :=
  ⟨[.letCallerLetStorageAddrReqEqLetMappingReqEqLitSetMappingStop
    "ownerSlot" "isIrmEnabledSlot" "sender" "currentOwner" "currentValue" "irm"
    0 4 1 "not owner" "already set"
    (by native_decide) (by native_decide) (by decide) (by decide) (by decide) (by decide)], rfl⟩

/-- The `enableLltv` function body is a `SupportedStmtList`. -/
theorem enableLltv_supported :
    SupportedStmtList morphoFields
      [ Stmt.letVar "sender" Expr.caller
      , Stmt.letVar "currentOwner" (Expr.storage "ownerSlot")
      , Stmt.require (Expr.eq (Expr.localVar "sender") (Expr.localVar "currentOwner")) "not owner"
      , Stmt.letVar "currentValue" (Expr.mappingUint "isLltvEnabledSlot" (Expr.param "lltv"))
      , Stmt.require (Expr.eq (Expr.localVar "currentValue") (Expr.literal 0)) "already set"
      , Stmt.require (Expr.lt (Expr.param "lltv") (Expr.literal 1000000000000000000)) "max LLTV exceeded"
      , Stmt.setMappingUint "isLltvEnabledSlot" (Expr.param "lltv") (Expr.literal 1)
      , Stmt.stop ] :=
  ⟨[.letCallerLetStorageAddrReqEqLetMappingUintReqEqLitReqLtSetMappingUintStop
    "ownerSlot" "isLltvEnabledSlot" "sender" "currentOwner" "currentValue" "lltv"
    0 5 1000000000000000000 1 "not owner" "already set" "max LLTV exceeded"
    (by native_decide) (by native_decide) (by decide) (by decide) (by decide) (by decide)], rfl⟩

/-- The `setAuthorization` function body is a `SupportedStmtList`. -/
theorem setAuthorization_supported :
    SupportedStmtList morphoFields
      [ Stmt.letVar "sender" Expr.caller
      , Stmt.letVar "currentValue"
          (Expr.mapping2 "isAuthorizedSlot" (Expr.localVar "sender") (Expr.param "authorized"))
      , Stmt.ite (Expr.param "newIsAuthorized")
          [ Stmt.require (Expr.eq (Expr.localVar "currentValue") (Expr.literal 0)) "already set"
          , Stmt.setMapping2 "isAuthorizedSlot" (Expr.localVar "sender") (Expr.param "authorized") (Expr.literal 1) ]
          [ Stmt.require (Expr.logicalNot (Expr.eq (Expr.localVar "currentValue") (Expr.literal 0))) "already set"
          , Stmt.setMapping2 "isAuthorizedSlot" (Expr.localVar "sender") (Expr.param "authorized") (Expr.literal 0) ]
      , Stmt.stop ] :=
  ⟨[.letCallerLetMapping2IteParamReqSetMapping2Stop
    "isAuthorizedSlot" "sender" "currentValue" "authorized" "newIsAuthorized"
    "already set" "already set" 6
    (by native_decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)], rfl⟩

end Morpho.Proofs.CompilationCorrectness
