import Morpho.Compiler.MacroSlice
import Verity.Core.Free.TypedIRCompilerCorrectness

/-!
# Compilation Correctness for Morpho Admin Functions

This module proves that 4 of the 5 admin function bodies generated by
`verity_contract MorphoViewSlice` are `SupportedStmtList`s, meaning the
generic typed-IR compilation-correctness theorem gives them free
compilation proofs (Links 2+3: EDSL ↔ IR ↔ Yul).

## Covered functions
1. **setOwner**: caller == owner, newOwner ≠ owner, setStorageAddr
2. **enableIrm**: caller == owner, mapping == 0, setMapping
3. **enableLltv**: caller == owner, mappingUint == 0, param < bound, setMappingUint
4. **setAuthorization**: caller, mapping2 read, ite bool, require, setMapping2

## Not yet covered
- **setFeeRecipient**: reads TWO different storage address fields (ownerSlot for auth,
  feeRecipientSlot for ≠ check) — needs a new `SupportedStmtFragment` constructor
  in verity that supports reading two distinct address storage fields.
  As of verity pin d1e6b409, only single-field-read patterns are supported.
-/

namespace Morpho.Proofs.CompilationCorrectness

open Compiler.CompilationModel
open Verity.Core.Free
open Morpho.Compiler.MacroSlice

-- DecidableEq chain needed for `native_decide` on field resolution
deriving instance DecidableEq for PackedBits
deriving instance DecidableEq for MappingKeyType
deriving instance DecidableEq for MappingType
deriving instance DecidableEq for StructMember
deriving instance DecidableEq for FieldType
deriving instance DecidableEq for Field

/-- Concrete storage field layout matching what `verity_contract MorphoViewSlice`
generates. Fields whose explicit slot matches their list position use `none`
so that `findFieldWithResolvedSlot` returns a `Field` with default `slot := none`,
matching the pattern expected by `SupportedStmtFragment` constructors.
Fields at non-matching positions (marketSlot, idToMarketParamsSlot) keep
their explicit `some` overrides. -/
def morphoFields : List Field :=
  [ ⟨"ownerSlot", FieldType.address, none, none, []⟩
  , ⟨"feeRecipientSlot", FieldType.address, none, none, []⟩
  , ⟨"marketSlot", FieldType.mappingTyped (.simple .uint256), some 3, none, []⟩
  , ⟨"idToMarketParamsSlot", FieldType.mappingTyped (.simple .uint256), some 8, none, []⟩
  , ⟨"isIrmEnabledSlot", FieldType.mappingTyped (.simple .address), none, none, []⟩
  , ⟨"isLltvEnabledSlot", FieldType.mappingTyped (.simple .uint256), none, none, []⟩
  , ⟨"isAuthorizedSlot", FieldType.mappingTyped (.nested .address .address), none, none, []⟩
  , ⟨"nonceSlot", FieldType.mappingTyped (.simple .address), none, none, []⟩
  ]

/-! ## SupportedStmtList witnesses -/

/-- The `setOwner` function body is a `SupportedStmtList`. -/
theorem setOwner_supported :
    SupportedStmtList morphoFields
      [ Stmt.letVar "sender" Expr.caller
      , Stmt.letVar "currentOwner" (Expr.storage "ownerSlot")
      , Stmt.require (Expr.eq (Expr.localVar "sender") (Expr.localVar "currentOwner")) "not owner"
      , Stmt.require (Expr.logicalNot (Expr.eq (Expr.param "newOwner") (Expr.localVar "currentOwner"))) "already set"
      , Stmt.setStorage "ownerSlot" (Expr.param "newOwner")
      , Stmt.stop ] :=
  ⟨[.letCallerLetStorageAddrReqEqReqNeqSetStorageAddrParamStop
    "ownerSlot" "sender" "currentOwner" "newOwner" "not owner" "already set" 0
    (by native_decide) (by decide) (by decide) (by decide)], rfl⟩

/-- The `enableIrm` function body is a `SupportedStmtList`. -/
theorem enableIrm_supported :
    SupportedStmtList morphoFields
      [ Stmt.letVar "sender" Expr.caller
      , Stmt.letVar "currentOwner" (Expr.storage "ownerSlot")
      , Stmt.require (Expr.eq (Expr.localVar "sender") (Expr.localVar "currentOwner")) "not owner"
      , Stmt.letVar "currentValue" (Expr.mapping "isIrmEnabledSlot" (Expr.param "irm"))
      , Stmt.require (Expr.eq (Expr.localVar "currentValue") (Expr.literal 0)) "already set"
      , Stmt.setMapping "isIrmEnabledSlot" (Expr.param "irm") (Expr.literal 1)
      , Stmt.stop ] :=
  ⟨[.letCallerLetStorageAddrReqEqLetMappingReqEqLitSetMappingStop
    "ownerSlot" "isIrmEnabledSlot" "sender" "currentOwner" "currentValue" "irm"
    0 4 1 "not owner" "already set"
    (by native_decide) (by native_decide) (by decide) (by decide) (by decide) (by decide)], rfl⟩

/-- The `enableLltv` function body is a `SupportedStmtList`. -/
theorem enableLltv_supported :
    SupportedStmtList morphoFields
      [ Stmt.letVar "sender" Expr.caller
      , Stmt.letVar "currentOwner" (Expr.storage "ownerSlot")
      , Stmt.require (Expr.eq (Expr.localVar "sender") (Expr.localVar "currentOwner")) "not owner"
      , Stmt.letVar "currentValue" (Expr.mappingUint "isLltvEnabledSlot" (Expr.param "lltv"))
      , Stmt.require (Expr.eq (Expr.localVar "currentValue") (Expr.literal 0)) "already set"
      , Stmt.require (Expr.lt (Expr.param "lltv") (Expr.literal 1000000000000000000)) "max LLTV exceeded"
      , Stmt.setMappingUint "isLltvEnabledSlot" (Expr.param "lltv") (Expr.literal 1)
      , Stmt.stop ] :=
  ⟨[.letCallerLetStorageAddrReqEqLetMappingUintReqEqLitReqLtSetMappingUintStop
    "ownerSlot" "isLltvEnabledSlot" "sender" "currentOwner" "currentValue" "lltv"
    0 5 1000000000000000000 1 "not owner" "already set" "max LLTV exceeded"
    (by native_decide) (by native_decide) (by decide) (by decide) (by decide) (by decide)], rfl⟩

/-- The `setAuthorization` function body is a `SupportedStmtList`. -/
theorem setAuthorization_supported :
    SupportedStmtList morphoFields
      [ Stmt.letVar "sender" Expr.caller
      , Stmt.letVar "currentValue"
          (Expr.mapping2 "isAuthorizedSlot" (Expr.localVar "sender") (Expr.param "authorized"))
      , Stmt.ite (Expr.param "newIsAuthorized")
          [ Stmt.require (Expr.eq (Expr.localVar "currentValue") (Expr.literal 0)) "already set"
          , Stmt.setMapping2 "isAuthorizedSlot" (Expr.localVar "sender") (Expr.param "authorized") (Expr.literal 1) ]
          [ Stmt.require (Expr.logicalNot (Expr.eq (Expr.localVar "currentValue") (Expr.literal 0))) "already set"
          , Stmt.setMapping2 "isAuthorizedSlot" (Expr.localVar "sender") (Expr.param "authorized") (Expr.literal 0) ]
      , Stmt.stop ] :=
  ⟨[.letCallerLetMapping2IteParamReqSetMapping2Stop
    "isAuthorizedSlot" "sender" "currentValue" "authorized" "newIsAuthorized"
    "already set" "already set" 6
    (by native_decide) (by decide) (by decide) (by decide) (by decide) (by decide) (by decide)], rfl⟩

end Morpho.Proofs.CompilationCorrectness
